{% set version = "1.4.7" %}

package:
  name: kafka-python
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/k/kafka-python/kafka-python-{{ version }}.tar.gz
  sha256: 2f29baad4b3efe05a2bb81ac268855aa01cbc68397f15bac77b494ffd7e2cada

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - kafka
    - kafka.consumer
    - kafka.coordinator
    - kafka.coordinator.assignors
    - kafka.metrics
    - kafka.metrics.stats
    - kafka.partitioner
    - kafka.producer
    - kafka.protocol
    - kafka.serializer
    - kafka.vendor

about:
  home: https://github.com/dpkp/kafka-python
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: 'Pure Python client for Apache Kafka'
  dev_url: https://github.com/dpkp/kafka-python
  doc_url: https://kafka-python.readthedocs.io/en/master/

extra:
  recipe-maintainers:
    - pmlandwehr
