travis:
  secure:
    BINSTAR_TOKEN: kR+73Pag46vv0+zNeOmSt7Pwzj6t/b4U5ax7tPosk1FSq7EUxBen8+ZFsCmTvPdBEizy5lQNgBgQfqZzz5LwB3PtN+VyXAP3ITYzSYr+oHbzLUfrIf9NAqWRtJjFtDlEKlHhwDhoTOOElrAzdLphKdpluByE3bG7w0eZy4bBFBXTd3P6hWszjHE9Bvrd3Ow/jTXzxo9CE3F1tzNKyI7zux+9tzBWVlMbADwAmygM3tKQDSAI3aOZPXJgIycmvs/i+SbfJzWE123/Halhgr9IkJ62c1nkzIMpquMWWcXAcKQXXh0wK1kWsConjkqYyaSnCsWGS6ZT3lXDx7xOL+pIUoz4M3vc3fjPDPqT1er+rXYtZEH+K3RfwClA/PiSKZU6vgQY7zlN08H/KHUhA+mXZO3gviZ2dLqoIvOPgxazinIPE3VRefXy5L6WF5j0e1yv2OsGxXUX9GXeog0hp2OaLYDkC7dKUASaWLI13vWVL08G3CBXNjvzcrk1JKkjTxUejGY9PONIXj5gnC+sMzKDPyGWbB6aUZBdVGvS4YCF8ukD+0tvPWj3NioPQY38qUfXJEhz+WkxMYLhehpS/myQt/IaPytJdtXFIQneL3OoUNrqy2YIRKYGwhi1lJQWlVxHAjbLJWzSlQgQ3IdHQs7zUynAdS5+5oQ0YRwb6Ir2g+o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
