travis:
  secure:
    BINSTAR_TOKEN: Lb2kjtgLubXoiLaPsI7uEXRZQqRu4jOfkMZaIZ18EvdHTvkGXrRKCEQWYpDuM/To9KLNWoq+eIJbRZIHGp9UcMVnpSUe4g3t85Ohwmfo/2OCW1CueM13HIBhMQtscNOFBaL7moI2pHvHNsdksSAIyVj756K8BkRXdVoBHHqDvpaH3NmEQUWDEb8DR9winJHwd7e919PkVye11BNJr4nIL53M9I5d252Sl+atU/QGT8ixJjrzgwORcSVrYw2vF2V4b2xsoJqP1sHBPLEsoETrFQJcEfwt28CXHD25w6+IYQemTwfNEMIaee6B4cwiEdvf59wACloZsHOPfO595TnQftm8OdDrGKZ5xB0zYxDm7UsUjhXNMz0pFXFYfBimzwnqIvvO+ewusdSM8wTCfDkdepdbCvBwzrXKcWLoQZF0TuBBlEsheAd9oIEZJQKRcdwUrsx0gI0WyP9pOzWLShELpDjVSw/sN6kcemyM6fixyspN6FY6XN9kgFtxHqdzw9tP95kYcwj0eQ2fPQ2gq18K1RoAScvkrq8/ZdfpaZ9JfgK32lKC09sa6/5RiNg2z6wn7omDKiDWch2z3jUDIncGZSDfdrAyoDiRgxRzwaRyAcDnpZRcscWx/j4nSurDLxR2rbeAemo/xBUCpZUSG17dpoeOm0+fQH0tcR8t71th3SI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
